### ISSUE TITLE
Add black and isort for code formatting

### ISSUE THREAD

**Issue by Alberto-Codes** [Alberto-Codes/game_pong#1]
We should set up black and isort for code consistency in this Pipenv project.

## Tasks  

- [x] Add dev packages to Pipfile:

    ```
    black = "*"
    isort = "*"  
    ```

- [x] Run `pipenv install` to add packages  

- [ ] Create pyproject.toml with:

    ```toml
    [tool.black]
    line-length = 88

    [tool.isort]
    profile = "black"
    ```

- [ ] Add scripts to Pipfile:  

    ```
    "format": "black . && isort .",
    "check-format": "black --check . && isort --check-only ."
    ```

- [ ] Integrate with pre-commit hooks
